
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_hw_fully_connected.ipynb

def mse(x, y):
    return (x.squeeze(-1) - y).pow(2).mean()

from torch import nn